# -*- coding: utf-8 -*-
"""Lab3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IvB_KEwsh2_LVuCtx_TILJjzeLPj4SVQ
"""

from google.colab import drive
drive.mount('/content/drive')

import nltk
from nltk.tokenize import word_tokenize

from nltk import sent_tokenize

nltk.download('punkt')

!pip install rnnmorph

from rnnmorph.predictor import RNNMorphPredictor

predictor = RNNMorphPredictor(language="ru")

root = '/content/drive/MyDrive/TSU/Lab_NLP/Lab3/'
filename = 'text.txt'

f = open(root+filename)

text = f.read()
text

tokens = word_tokenize(text)
res = predictor.predict(tokens)

res

lemmas = []
pos = ['NOUN', 'AJD']
for token in res:
  nform = token.normal_form
  if token.pos in pos:
    lemmas.append((nform, token.tag))

lemmas

def extract_variables(word):
  variables = {
      'Case': None,
      'Gender': None,
      'Number': None
  }
  key_value_pairs = word.split('|')
  for pair in key_value_pairs:
    key, value = pair.split('=')
    variables[key] = value
  return variables

all_sentence = sent_tokenize(text)
all_sentence

pos = ['NOUN', 'ADJ']

for sentence in all_sentence:
  print(f"Sentence: {sentence}")
  word_in_sentence = word_tokenize(sentence)
  res = predictor.predict(word_in_sentence)

  lemmas = []
  for word in res:
    nform = word.normal_form
    if word.pos in pos:
      lemmas.append((nform, word.tag))
  matching_pairs = []
  for i in range(len(lemmas) - 1):
    word1 = lemmas[i][0]
    tag1 = lemmas[i][1]

    word2 = lemmas[i + 1][0]
    tag2 = lemmas[i + 1][1]

    t1 = extract_variables(tag1)
    t2 = extract_variables(tag2)

    if(t1['Case'] == t2['Case'] and t1['Gender'] == t2['Gender'] and t1['Number'] == t2['Number']):
      matching_pairs.append((word1, word2))

  for pair in matching_pairs:
    print(" ".join(pair))

  print()

"""# Результаты лабы 1

Sentence: Когда человек сознательно или интуитивно выбирает себе в жизни какую-то цель, жизненную задачу, он невольно дает себе оценку.

задача оценка

Sentence: По тому, ради чего человек живет, можно судить и о его самооценке - низкой или высокой.

тот человек

низкий высокий

Sentence: Если человек живет, чтобы приносить людям добро, облегчать их страдания, давать людям радость, то он оценивает себя на уровне этой своей человечности.

человек человек

этот свой

Sentence: Он ставит себе цель, достойную человека.

достойный человек

Sentence: Только такая цель позволяет человеку прожить свою жизнь с достоинством и получить настоящую радость.

Sentence: Да, радость!

Sentence: Подумайте: если человек ставит себе задачей увеличивать в жизни добро, приносить людям счастье, какие неудачи могут его постигнуть?

Sentence: Не тому помочь?

Sentence: Но много ли людей не нуждаются в помощи?

Sentence: Если жить только для себя, своими мелкими заботами о собственном благополучии, то от прожитого не останется и следа.

Sentence: Если же жить для других, то другие сберегут то, чему служил, чему отдавал силы.

другой другой

Sentence: Можно по-разному определять цель своего существования, но цель должна быть.

Sentence: Надо иметь и принципы в жизни.

Sentence: Одно правило в жизни должно быть у каждого человека, в его цели жизни, в его принципах жизни, в его поведении: надо прожить жизнь с достоинством, чтобы не стыдно было вспоминать.

Sentence: Достоинство требует доброты, великодушия, умения не быть эгоистом, быть правдивым, хорошим другом, находить радость в помощи другим.

великодушие умение

эгоист правдивый

правдивый хороший

хороший друг

радость помощь

Sentence: Ради достоинства жизни надо уметь отказываться от мелких удовольствий и немалых тоже… Уметь извиняться, признавать перед другими ошибку - лучше, чем врать.

Sentence: Обманывая, человек прежде всего обманывает самого себя, ибо он думает, что успешно соврал, а люди поняли и из деликатности промолчали.

сам человек

Sentence: Жизнь - прежде всего творчество, но это не значит, что каждый человек, чтобы жить, должен родиться художником, балериной или ученым.

человек должный

должный художник

Sentence: Можно творить просто добрую атмосферу вокруг себя.

Sentence: Человек может принести с собой атмосферу подозрительности, какого-то тягостного молчания, а может внести сразу радость, свет.

атмосфера подозрительность

Sentence: Вот это и есть творчество.

# Вывод
Некоторые слова совпадают. Хотя в некоторые предложения оно очень хорошо работает чем результату первой лабы.
"""